var value = [];
value[0] = "skjd";
value[1] = 45454;
value[2] = "chintu";
value[3] = 3436;
var newarr;
newarr[0] = 1;
newarr[1] = "10";
console.log("value 1 is " + value[0] + " value 2 is " + value[1] + " value 3 is " + value[2] + " value 4 is " + value[3]);
console.log("NewArray value 1 is=" + newarr[0] + " NewArray value 2 is " + newarr[1]);
